services:
  staging:
    build: /etc/docker/container/lp
    ports:
      - "3001:3001"
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.lp.rule=Host(`staging.arbispotter.com`)"
      - "traefik.http.services.lp.loadbalancer.server.port=3001"
      - "traefik.http.middlewares.lp-headers.headers.customrequestheaders.X-Real-IP=$$remote_addr"
      - "traefik.http.middlewares.lp-headers.headers.customrequestheaders.X-Forwarded-For=$$proxy_add_x_forwarded_for"
      - "traefik.http.middlewares.lp-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.lp-headers.headers.customrequestheaders.X-Forwarded-Host=$$host"
      - "traefik.http.middlewares.lp-headers.headers.customrequestheaders.X-Frame-Options=SAMEORIGIN"
    networks:
      - traefik_web
networks:
  traefik_web:
    external: true