services:
      live:
        build: /etc/docker/container/lp-live
        ports:
          - "4001:3001"
        labels: 
          - "traefik.enable=true"
          - "traefik.http.routers.lp-live.rule=Host(`www.arbispotter.com`)"
          - "traefik.http.services.lp-live.loadbalancer.server.port=3001"
          - "traefik.http.middlewares.lp-liveheaders.headers.customrequestheaders.X-Real-IP=$$remote_addr"
          - "traefik.http.middlewares.lp-liveheaders.headers.customrequestheaders.X-Forwarded-For=$$proxy_add_x_forwarded_for"
          - "traefik.http.middlewares.lp-liveheaders.headers.customrequestheaders.X-Forwarded-Proto=https"
          - "traefik.http.middlewares.lp-liveheaders.headers.customrequestheaders.X-Forwarded-Host=$$host"
          - "traefik.http.middlewares.lp-liveheaders.headers.customrequestheaders.X-Frame-Options=SAMEORIGIN"
        
          # Redirect router for arbispotter.com to www.arbispotter.com
          - "traefik.http.routers.lp-redirect.rule=Host(`arbispotter.com`)"
          - "traefik.http.routers.lp-redirect.entrypoints=https"
          - "traefik.http.routers.lp-redirect.middlewares=redirect-lp-to-www,default@file"

          # Middleware to handle the redirection
          - "traefik.http.middlewares.redirect-lp-to-www.redirectregex.regex=^https?://arbispotter\\.com(.*)"
          - "traefik.http.middlewares.redirect-lp-to-www.redirectregex.replacement=https://www.arbispotter.com$${1}"
          - "traefik.http.middlewares.redirect-lp-to-www.redirectregex.permanent=true"
        
        
        networks:
          - traefik_web
networks:
  traefik_web:
    external: true