name: Deploy landing page
on:
  push:
    branches:
      - staging
      - main
jobs:
  deploy-lp-live:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy lp-live
        timeout-minutes: 30
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST_LIVE}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_FE_PK }}
          passphrase: ${{ secrets.PASSPHRASE }}
          command_timeout: 30m
          script: |
            docker builder prune -f
            git --work-tree=/etc/docker/container/lp-live --git-dir=/etc/docker/container/lp-live/.git reset --hard
            git --work-tree=/etc/docker/container/lp-live --git-dir=/etc/docker/container/lp-live/.git pull
            cd /etc/docker/container/lp-live
            docker compose -f docker-compose.lp-live.yml up --build -d